# Generated by Django 3.0.2 on 2020-10-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201030_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
    ]
